id: I1A1EFFFF
legacy_id: P003244
ocr_import_info:
  bdrc_scan_id: W21809
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T01:39:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T14:32:32.574672+00:00'
last_modified: 2022-09-01 22:42:27.119976
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W21809
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW21809
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། རབ་གསལ་ཟླ་བ།
  author: དིལ་མགོ་མཁྱེན་བརྩེ་བཀྲ་ཤིས་དཔལ་འབྱོར།
statistics:
  ocr_word_mean_confidence_index: 0.905635492272971
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I1839:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1839
      total_pages: 633
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I1839.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8893598349369359
    legacy_id: v009
  I1845:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1845
      total_pages: 703
      volume_number: 15
      volume_pages_bdrc_intro: 2
    order: 15
    base_file: I1845.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9015334766809823
    legacy_id: v015
  I1831:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1831
      total_pages: 637
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1831.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9086121262398552
    legacy_id: v001
  I1832:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1832
      total_pages: 573
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1832.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9256231967372499
    legacy_id: v002
  I1835:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1835
      total_pages: 655
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1835.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9085987459193289
    legacy_id: v005
  I1853:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1853
      total_pages: 619
      volume_number: 23
      volume_pages_bdrc_intro: 2
    order: 23
    base_file: I1853.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9178316397066949
    legacy_id: v023
  I1834:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1834
      total_pages: 661
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1834.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9154574341695023
    legacy_id: v004
  I1846:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1846
      total_pages: 724
      volume_number: 16
      volume_pages_bdrc_intro: 2
    order: 16
    base_file: I1846.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9075112126931366
    legacy_id: v016
  I1854:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1854
      total_pages: 653
      volume_number: 24
      volume_pages_bdrc_intro: 2
    order: 24
    base_file: I1854.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9165105276121213
    legacy_id: v024
  I1850:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1850
      total_pages: 515
      volume_number: 20
      volume_pages_bdrc_intro: 2
    order: 20
    base_file: I1850.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.889028077670988
    legacy_id: v020
  I1840:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1840
      total_pages: 679
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I1840.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9045898374148631
    legacy_id: v010
  I1851:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1851
      total_pages: 621
      volume_number: 21
      volume_pages_bdrc_intro: 2
    order: 21
    base_file: I1851.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8948357987812482
    legacy_id: v021
  I1855:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1855
      total_pages: 617
      volume_number: 25
      volume_pages_bdrc_intro: 2
    order: 25
    base_file: I1855.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9199620224622632
    legacy_id: v025
  I1843:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1843
      total_pages: 715
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I1843.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8967457844425162
    legacy_id: v013
  I1838:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1838
      total_pages: 617
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1838.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8926718293177627
    legacy_id: v008
  I1849:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1849
      total_pages: 635
      volume_number: 19
      volume_pages_bdrc_intro: 2
    order: 19
    base_file: I1849.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.892481590999084
    legacy_id: v019
  I1842:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1842
      total_pages: 677
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I1842.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.897121600482003
    legacy_id: v012
  I1833:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1833
      total_pages: 629
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1833.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9313911919362626
    legacy_id: v003
  I1841:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1841
      total_pages: 691
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I1841.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9182691286866667
    legacy_id: v011
  I1848:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1848
      total_pages: 635
      volume_number: 18
      volume_pages_bdrc_intro: 2
    order: 18
    base_file: I1848.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8810510939150065
    legacy_id: v018
  I1837:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1837
      total_pages: 599
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1837.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8854772548469528
    legacy_id: v007
  I1847:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1847
      total_pages: 597
      volume_number: 17
      volume_pages_bdrc_intro: 2
    order: 17
    base_file: I1847.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8899765355249322
    legacy_id: v017
  I1852:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1852
      total_pages: 637
      volume_number: 22
      volume_pages_bdrc_intro: 2
    order: 22
    base_file: I1852.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9131266944505919
    legacy_id: v022
  I1844:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1844
      total_pages: 689
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I1844.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9083016820935347
    legacy_id: v014
  I1836:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1836
      total_pages: 635
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1836.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8958644012984176
    legacy_id: v006
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
