id: I1A1EFFFF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T01:46:33+00:00'
last_modified: '2022-06-07T18:37:02.085870+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21809
  title: གསུང་འབུམ། རབ་གསལ་ཟླ་བ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '5421':
      image_group_id: I1831
      title: ''
      total_pages: 637
      order: 1
      base_file: 5421.txt
    83B8:
      image_group_id: I1832
      title: ''
      total_pages: 573
      order: 2
      base_file: 83B8.txt
    245A:
      image_group_id: I1833
      title: ''
      total_pages: 629
      order: 3
      base_file: 245A.txt
    75BD:
      image_group_id: I1834
      title: ''
      total_pages: 661
      order: 4
      base_file: 75BD.txt
    5AF5:
      image_group_id: I1835
      title: ''
      total_pages: 655
      order: 5
      base_file: 5AF5.txt
    '6740':
      image_group_id: I1836
      title: ''
      total_pages: 635
      order: 6
      base_file: 6740.txt
    AFA9:
      image_group_id: I1837
      title: ''
      total_pages: 599
      order: 7
      base_file: AFA9.txt
    EBFD:
      image_group_id: I1838
      title: ''
      total_pages: 617
      order: 8
      base_file: EBFD.txt
    93C8:
      image_group_id: I1839
      title: ''
      total_pages: 633
      order: 9
      base_file: 93C8.txt
    0A85:
      image_group_id: I1840
      title: ''
      total_pages: 679
      order: 10
      base_file: 0A85.txt
    2CDA:
      image_group_id: I1841
      title: ''
      total_pages: 691
      order: 11
      base_file: 2CDA.txt
    7BA7:
      image_group_id: I1842
      title: ''
      total_pages: 677
      order: 12
      base_file: 7BA7.txt
    57FD:
      image_group_id: I1843
      title: ''
      total_pages: 715
      order: 13
      base_file: 57FD.txt
    11B7:
      image_group_id: I1844
      title: ''
      total_pages: 689
      order: 14
      base_file: 11B7.txt
    009A:
      image_group_id: I1845
      title: ''
      total_pages: 703
      order: 15
      base_file: 009A.txt
    0F9E:
      image_group_id: I1846
      title: ''
      total_pages: 724
      order: 16
      base_file: 0F9E.txt
    D70C:
      image_group_id: I1847
      title: ''
      total_pages: 597
      order: 17
      base_file: D70C.txt
    A57E:
      image_group_id: I1848
      title: ''
      total_pages: 635
      order: 18
      base_file: A57E.txt
    FAB6:
      image_group_id: I1849
      title: ''
      total_pages: 635
      order: 19
      base_file: FAB6.txt
    7E68:
      image_group_id: I1850
      title: ''
      total_pages: 515
      order: 20
      base_file: 7E68.txt
    A041:
      image_group_id: I1851
      title: ''
      total_pages: 621
      order: 21
      base_file: A041.txt
    '6241':
      image_group_id: I1852
      title: ''
      total_pages: 637
      order: 22
      base_file: 6241.txt
    BDDE:
      image_group_id: I1853
      title: ''
      total_pages: 619
      order: 23
      base_file: BDDE.txt
    FD47:
      image_group_id: I1854
      title: ''
      total_pages: 653
      order: 24
      base_file: FD47.txt
    2D46:
      image_group_id: I1855
      title: ''
      total_pages: 617
      order: 25
      base_file: 2D46.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
